version: "3"
services:
  setup:
    build:
      context: setup/
      args:
        ELASTIC_VERSION: 8.4.2
    init: true
    volumes:
      - setup:/state:Z
    environment:
      ELASTIC_PASSWORD: "techmaster"
      LOGSTASH_INTERNAL_PASSWORD: "techmaster"
      KIBANA_SYSTEM_PASSWORD: "techmaster"
    networks:
      - lesson-05
    depends_on:
      - elasticsearch
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.4.2
    volumes:
      - ./elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro,z
      - elasticsearch:/usr/share/elasticsearch/data:z
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: -Xms512m -Xmx512m
      # Bootstrap password.
      # Used to initialize the keystore during the initial startup of
      # Elasticsearch. Ignored on subsequent runs.
      ELASTIC_PASSWORD: "techmaster"
      # Use single node discovery in order to disable production mode and avoid bootstrap checks.
      # see: https://www.elastic.co/guide/en/elasticsearch/reference/current/bootstrap-checks.html
      discovery.type: single-node
    networks:
      - lesson-05
volumes:
  elasticsearch:
  setup:
networks:
  lesson-05: