version: "3.8"

services:
  filebeat:
    image: docker.elastic.co/beats/filebeat:8.4.2
    user: root
    volumes:
    - ./filebeat.yml:/usr/share/filebeat/filebeat.yml
    - ./error-java.log:/var/log/error-java.log
    networks:
      - elk_ELK-lesson-04
networks:
  elk_ELK-lesson-04:
    external: true