version: '3.7'

services:
  kibana:
    image: docker.elastic.co/kibana/kibana:8.4.2
    volumes:
      - ./kibana.yml:/usr/share/kibana/config/kibana.yml:ro,Z
    ports:
      - "5601:5601"
    environment:
      KIBANA_SYSTEM_PASSWORD: "yxcxxJFmUV7CaVsoXSb3"
      # Fleet plugin
      KIBANA_FLEET_SETUP: '1'
    networks:
      - elasticsearch_lesson5

networks:
  elasticsearch_lesson5:
    external: true
