version: "3"
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.4.2
    environment:
      - xpack.security.enabled=false  # security is disabled
      - discovery.type=single-node # single node
    mem_limit: 1073741824 # container memory limit 1G
    ports:
      - 9200:9200
    volumes:
      - data-elasticsearch:/usr/share/elasticsearch/data # mount data volume
    networks:
      - ELK-lesson-06
  kibana:
    image: docker.elastic.co/kibana/kibana:8.4.2
    environment:
      - SERVERNAME=kibana
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - 5601:5601
    networks:
      - ELK-lesson-06
  logstash:
    image: docker.elastic.co/logstash/logstash:8.4.3
    volumes:
      - ./logstash.yml:/usr/share/logstash/config/logstash.yml:ro,Z
      - ./pipeline:/usr/share/logstash/pipeline:ro,Z
    environment:
      LS_JAVA_OPTS: -Xms256m -Xmx256m
    ports:
      - "5044:5044"
      - "50000:50000/tcp"
      - "50000:50000/udp"
      - "9600:9600"
    networks:
      - ELK-lesson-06
volumes:
  data-elasticsearch:
    driver: local
networks:
  ELK-lesson-06: