filebeat.inputs:
- type: container
  paths: 
    - '/var/lib/docker/containers/*/*.log'

output.elasticsearch:
  hosts: ["18.140.233.111:9200"]
  indices:
    - index: "filebeat-%{[agent.version]}-%{+yyyy.MM.dd}"
