version: "3.8"

services:
  filebeat:
    image: docker.elastic.co/beats/filebeat:8.4.2
    container_name: filebeat
    user: root
    volumes:
    - ./filebeat.yml:/usr/share/filebeat/filebeat.yml
    - /home/ubuntu/ELK-tech-master/Lesson-2/nginx/log:/var/log/nginx/