version: '2.2'
services:
  php:
    build: .
    environment:
      - ELASTIC_APM_SERVICE_NAME="PHP techmaster"
      - ELASTIC_APM_SERVER_URL=http://apm:8200
      - ELASTIC_APM_SECRET_TOKEN=""
    ports:
    - 80:80
    networks:
    - elk_default
  mariadb:
    image: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=techmaster
      - MYSQL_DATABASE=wordpress
    volumes:
    - database:/var/lib/mysql
    networks:
    - elk_default
volumes:
  database:
    driver: local
networks:
  elk_default:
    external: true
